version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres-zeroq
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"

  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zeroq-container
    ports:
      - "3000:3000"
    volumes:
      - ./init-script.sql:/docker-entrypoint-initdb.d/init-script.sql
    env_file:
      - .env
    depends_on:
      - postgres